# Generated by Django 5.1.1 on 2024-09-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyBuyApp', '0003_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=550),
        ),
    ]
